function [AJ, BJ, AM, BM] = hexahedron(nodes, P, J, M)
% Evaluate the flux density B and the magnetic potential A generated by an hexahedron (8 vertex) with uniform current J and uniform magnetization M
% Hexahedron:
%
%        z
% 5----------8
% |\     ^   |\
% | \    |   | \
% |  \   |   |  \
% |   6------+---7
% |   |  +-- |-- | -> y
% 1---+---\--4   |
%  \  |    \  \  |
%   \ |     \  \ |
%    \|      x  \|
%     2----------3
%
% INPUT
% nodes: the coordinates of the 8 vertex          | DIM: 3 x 8
% P: field point                                  | DIM: 3 x 1
% J: Uniform Current Density                      | DIM: 3 x 1
% M: Uniform Magnetization                        | DIM: 3 x 1
%
% OUTPUT
% AJ: Vector potential due to the current         | DIM: 3 x 1
% BJ: Magnetic field due to the current           | DIM: 3 x 1
% AM: Vector potential due to the magnetization   | DIM: 3 x 1
% BM: Magnetic field due to the magnetization     | DIM: 3 x 1
%
% -----------------------------------------------------------
% REFERENCES:
% Fabbri, Magnetic Flux Density and Vector Potential of Uniform Polyhedral Sources,Ieee Tmag, vol.44 No.1, 2008
% The paper presents the following important equations:
%
% Eq. 5
% A = (u0 / 8pi) * sum_faces(J * (rf - r) · nf)
% Eq. 9
% B = (u0 / 4pi) * sum_faces(Wf * J x nf)
% Eq 11
% A = (u0 / 4pi) * sum_faces(Wf * M x nf)
% Eq 12
% B = - (u0 / 4pi) * sum_faces( (M x nf) x grad Wf)
%
% Eq. 17
% Wf = sum_edges( we * nf x (re - r) · ue) - Om * (rf - r) · nf
%
% Eq. 25
% graf Wf = sum_edges( we * nf x ue) + Om * nf
% -------------------------------------------------------------
%
% Last Modified: 08oct14
%
%

% Each hexahedron has 6 faces
nFaces = 6;
% Each face has 4 edges
nEdges = 4;

% Structure with 6 quadruples. A column identifies a single face with the nodes constituting it. The faces are couter-clockwise oriented
faces = zeros(4,6);

faces(1, 1:6) = [1 2 1 3 5 1];
faces(2, 1:6) = [4 3 5 4 6 2];
faces(3, 1:6) = [3 7 8 8 7 6];
faces(4, 1:6) = [2 6 4 7 8 5];

coeffAJ = zeros(3, nFaces);
coeffBJ = zeros(3, nFaces);
coeffAM = zeros(3, nFaces);
coeffBM = zeros(3, nFaces);

r = P;

for faceIndex = 1:nFaces
    
    % FACES VARIABLES
    
    % Wf = sum_edges( we * nf x (re - r) · ue) - Omega * (rf - r) · nf
    Wf = 0;
    
    % graf Wf = sum_edges( we * nf x ue) + Om * nf
    gradWf = zeros(3, 1);
    
    % 4 nodes of the face
    N1 = nodes(:,faces(1,faceIndex));
    N2 = nodes(:,faces(2,faceIndex));
    N3 = nodes(:,faces(3,faceIndex));
    N4 = nodes(:,faces(4,faceIndex));
    
    % rf is an arbitrary point on the face: it is set in the face baricenter
    rf = (N1 + N2 + N3 + N4)./4;
    
    % normal to the face
    nf = cross(N2 - N1, N3 - N2);
    nf = nf./norm(nf);
    
    % solid Angles of the faces.
    om = solidAngle(N1, N2, N3, r) + solidAngle(N1, N3, N4, r);
    
    for edgeIndex = 1:nEdges
        
        r1 = nodes(:, faces(edgeIndex,faceIndex));
        
        if edgeIndex < nEdges
            r2 = nodes(:, faces(edgeIndex + 1,faceIndex));
        else
            r2 = nodes(:, faces(1, faceIndex));
        end
        
        % re is an arbitrary point on the edge: it is set as the first node
        re = r1;
        
        % Tangents to the edges
        ue = r2 - r1;
        ue = ue./norm(ue);
        
        %
        coeffwe = dot(cross(nf,(re - r)), ue);
        we = wefun(r1, r2,r);
        
        % sum_edges( we * nf x (re - r) · ue); Eq. U17
        Wf = Wf + coeffwe * we;
        
        % graf Wf = sum_edges( we * nf x ue); Eq. U25
        gradWf = gradWf + we * cross(nf, ue);
        
    end
    
    % coeffOm = (rf - r) · nf ; See Eq. U17
    coeffOm = dot((rf - r),nf);
    Wf = Wf - coeffOm * om;
    
    % graf Wf = sum_edges( we * nf x ue) + Om * nf: See Eq. U25
    gradWf = gradWf + (nf * om);
    
    % coeffAJ = J * (rf - r) · nf * Wf;      See Eq. 5
    % coeffBJ = J x nf * Wf;                 See Eq. 9
    % coeffAM = M x nf * Wf;                 See Eq. 11
    % coeffBM = (M x nf) x grad Wf;          See Eq. 12
    coeffAJ(:, faceIndex) = dot((rf - r), nf) * J * Wf;
    coeffBJ(:, faceIndex) = cross(J, nf) * Wf;
    coeffAM(:, faceIndex) = cross(M, nf) * Wf;
    coeffBM(:, faceIndex) = cross(cross(M, nf), gradWf);
end

AJ = (1e-7 / 2 * sum(coeffAJ, 2));        % To be validated
BJ = 1e-7 * sum(coeffBJ, 2);             % Validated against Brick Babic
AM = 1e-7 * sum(coeffAM, 2);             % To be validated
BM = -1e-7 * sum(coeffBM, 2);            % Validated against Brick Haznadar

end

function we=wefun(vect_r1,vect_r2,vect_r)
% Evaluate the function of eq. 18 of the paper Fabbri, Magnetic Flux Density and Vector Potential of Uniform Polyhedral Sources,Ieee Tmag, vol.44 No.1, 2008

num = (norm(vect_r2-vect_r)+norm(vect_r1-vect_r)+norm(vect_r2-vect_r1));
den = (norm(vect_r2-vect_r)+norm(vect_r1-vect_r)-norm(vect_r2-vect_r1));
we=log(num/den);

end

function Om = solidAngle(R1, R2, R3, P)
% Evaluates the solid angle of a triangular surface of vertex R1, R2, R3 seen from the point P
%
% INPUT
% R1, R2, R3: vertex of the surface             | DIM: 3 x 1
% P: view point                                 | DIM: 3 x 1
%
% OUTPUT
% Om: solid angle
%

Omt_num=dot((R1-P),cross((R2-P),(R3-P)));

Omt_den=(norm(R1-P)*norm(R2-P)*norm(R3-P)+...
    norm(R3-P)*dot((R1-P),(R2-P))+...
    norm(R2-P)*dot((R1-P),(R3-P))+...
    norm(R1-P)*dot((R2-P),(R3-P)));

Om = 2 * atan2(Omt_num, Omt_den);

end